build: 
  verbosity: detailed

os: Visual Studio 2015

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

  ############################################################################
  # Install a recent TBB
  ############################################################################
  - set TBB_URL="https://github.com/01org/tbb/releases/download/2017_U5/tbb2017_20170226oss_win.zip"
  - appveyor DownloadFile %TBB_URL% -FileName tbb.zip
  - 7z x tbb.zip -oC:\projects\deps > nul
  - move C:\projects\deps\tbb2017* C:\projects\deps\tbb # Move to a version-agnostic directory
  - dir C:\projects\deps
  - call "C:\projects\deps\tbb\bin\tbbvars.bat" intel64 vs2015

  ############################################################################
  # Setup the path to Clang-cl
  ############################################################################
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - clang-cl -v

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\Zcode


build_script:
  - cmake -G "NMake Makefiles" -DCMAKE_CXX_COMPILER=clang-cl -DDOWNLOAD_GTEST=ON .
  - nmake test_zcode
  - cd test

test_script:
  - .\test_zcode > C:\projects\Zcode\test.log 2>&1

on_failure:
  - dir C:\projects\Zcode
  - ps: get-content C:\projects\Zcode\test.log